### ISSUE TITLE
Can't download maven

### ISSUE THREAD

**Issue by Turiok** [gantsign/ansible-role-maven#116]
Hello,

Thx for your role.
I'm not an ansible expert.
But when the playbook try to download maven, it failed. 
I supposed it was because I have a slow connection. 
If I add a timeout longer on "download Maven" task. It works.

Output when it's failed :
```shell
 An exception occurred during task execution. To see the full traceback, use -vvv. The error was: timeout: timed out
fatal: [dev_188]: FAILED! => changed=false
  elapsed: 0
  msg: 'failed to create temporary content file: timed out'
```

Workaround possible :
Hello,

Thx for your role.
I'm not an ansible expert.
But when the playbook try to download maven, it failed. 
I supposed it was because I have a slow connection. 
If I add a timeout longer on "download Maven" task. It works.

Output when it's failed :
```yaml
- name: download Maven
  get_url:
    url: '{{ maven_mirror }}/{{ maven_redis_filename }}'
    dest: '{{ maven_download_dir }}/{{ maven_redis_filename }}'
    sha256sum: '{{ maven_redis_sha256sum }}'
    force: no
    use_proxy: yes
    validate_certs: yes
    timeout: {{ maven_download_timeout }}
    mode: 'u=rw,go=r'
```
